### ISSUE TITLE
[SG NOI 2021 Finals] Subtask of sample test cases for task pond

### ISSUE THREAD

**Issue by prabowo02** [noisg/sg_noi_archive#11]
For samples 1 and 2 of SG NOI 2021 Finals problem pond, they seem to not satisfy subtask 5, but the task statement is saying otherwise.

Is it the description of subtask 5 that is incorrect, or it's the sample descriptions that are incorrect?

**Comment by ranaldmiao** [comment]
@btzy

**Comment by btzy** [comment]
Yes, the sample test cases 1 and 2 incorrectly state that they satisfy subtask 5.  They actually do not satisfy subtask 5.
