### ISSUE TITLE
Invalid test case of SG NOI 2021 Finals Pond

### ISSUE THREAD

**Issue by prabowo02** [noisg/sg_noi_archive#13]
In SG NOI 2021 Finals problem Pond, the test case `5-7.in` does not satisfy subtask 5.

Subtask 5 has the constraint `K <= min(N, 2000)`, but the value of N and K in that test case is `298944 298944`

**Comment by ranaldmiao** [comment]
@btzy

**Comment by btzy** [comment]
Thanks for raising this, test 5-7 is indeed invalid.
